<?php

namespace fibe\CommunityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationRepository extends EntityRepository
{




    /**
     * filtering with all parameters difned
     * @param $qb , query builder to add the filter to
     * @param $params , the field to filter on
     * @return $qb, modified query builder
     */
    public function filter($qb, $params)
    {
        if (isset($params['mainEventId'])) {
            $qb->leftJoin('qb.organizationVersions', 'orgv');
            $qb->leftJoin('orgv.organizationVersionOwner' , 'pers');
            $qb->leftJoin('pers.roles' , 'rol');
            $qb->andWhere('rol.mainEvent = (:MainEventId)');
            $qb->setParameter('MainEventId', $params['mainEventId']);
        }
        return $qb;
    }
}
