<?php

namespace fibe\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{


  /**
   * filtering with all parameters defined
   * @param $qb , query builder to add the filter to
   * @param $params , the field to filter on
   * @return $qb, modified query builder
   */
  public function filter($qb, $params)
  {
    if (isset($params['mainEventId']))
    {
      $qb->andWhere('qb.mainEvent = :mainEventId');
      $qb->setParameter('mainEventId', $params['mainEventId']);
    }

    if (isset($params['id']))
    {
      $qb
        ->andWhere('qb.id = :id')
        ->setParameter('id', $params['id']);
    }

    if (isset($params['categoryVersionId']))
    {
      $qb->leftJoin('qb.category', 'c')
        ->andWhere('c.id = :categoryId')
        ->setParameter('categoryId', $params['categoryId']);
    }
    return $qb;
  }

}