<?php

namespace fibe\ContentBundle\Repository;

use Doctrine\ORM\EntityRepository;
use fibe\ContentBundle\Repository\LocationRepository;

/**
 * MainEventLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainEventLocationRepository extends EntityRepository
{
}
