imports:
    - { resource: parameters.yml }
    - { resource: parameters_common.yml }
    - { resource: security.yml }
    - { resource: @fibeEventBundle/Resources/config/services.yml}

hwi_oauth:
    #this is my custom user provider, created from FOSUBUserProvider - will manage the 
    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
    #and also, the connecting part (get the token and the user_id)
    connect:
        account_connector: my_user_provider
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
    resource_owners: %social_networks%

assetic:
    node: %path_to_node%


framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection:
        enabled: false # globally disable csrf protection
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         
        handler_id: ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    # strict_variables: %kernel.debug%
    form:
        resources:
            - form_global_theme.html.twig
            - 'fibeSecurityBundle:Form:fields.html.twig'
            - LexikFormFilterBundle:Form:form_div_layout.html.twig


# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        memory: true
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    auth_mode:  %mailer_auth_mode% 
    encryption: %mailer_encryption%
    username:   %mailer_username%
    password:   %mailer_password%


twig:
    form:
        resources:


fos_user:
    db_driver:     orm                              # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                             # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    fibe\SecurityBundle\Entity\User  # La classe de l'entité User que nous utilisons         
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        # Permet de définir le template de l'email à envoyer (en html)
        email:
              template: fibeSecurityBundle:Mail:resetting_password.email.twig
    registration:
        form:
            type: fibe_user_registration
        confirmation:
            enabled:   true # change to true for required email confirmation
            template:   fibeSecurityBundle:Mail:confirmation.email.twig
    profile:
        form:
            type:  fibe_user_profile
    from_email:
         # Adresse de l'expediteur
         address:      noreply@sympozer.com
         # Nom de l'expediteur
         sender_name:  Sympozer

sensio_framework_extra:
    view:
        annotations: false
    request: { converters: true }

fos_rest:
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
            xml:  true
    format_listener:
        rules:
            - { path: ^/, priorities: [ html, json, xml, css, js ], fallback_format: ~, prefer_extension: true }
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true
    disable_csrf_role: ROLE_API

jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUB"