<?php


namespace fibe\SecurityBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 */
class TeammateRepository extends EntityRepository
{

    /**
     * filtering with all parameters defined
     * @param QueryBuilder $qb , query builder to add the filter to
     * @param $params , the field to filter on
     * @return QueryBuilder $qb, modified query builder
     */
    public function filter(QueryBuilder $qb, $params)
    {

        if (isset($params['mainEventId']))
        {
            $qb->leftJoin('qb.team', 'team')
                ->leftJoin('team.mainEvent', 'me')
                ->andWhere('me.id = (:mainEventId)')
                ->setParameter('mainEventId', $params['mainEventId']);
        }

        return $qb;
    }
}
