<?php

namespace fibe\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryGlobalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * filtering with all parameters defined
     * @param $qb , query builder to add the filter to
     * @param $params , the field to filter on
     * @return $qb, modified query builder
     */
    public function filter($qb, $params)
    {
        if (isset($params['mainEventId'])) {
            $qb->leftJoin('qb.events', 'events')
                ->andWhere('events.mainEvent = (:mainEventId)')
                ->setParameter('mainEventId', $params['mainEventId']);
            return $qb;
        }

        return $qb;
    }


}
